<!doctype html public "-//w3c//dtd html 4.0 transitional//en">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
		<title>Stella: &quot;A Multi-Platform Atari 2600 VCS Emulator&quot;</title>
		<link href="cssscreen.css" rel="stylesheet" media="screen">
		<link href="cssprint.css" rel="stylesheet" media="print">
	</head>
	<body id="stable">
		<div class="rightcolumn">
			<div class="header"><?php include("header.php"); ?></div>
			<div class="content">

<!---------------------------------------------------------------->
<table BORDER=0 CELLPADDING=6 WIDTH="100%">

	<tr>
		<td><b>Latest&nbsp;Release (v/ 4.0)</b></td>
		<td>&nbsp;</td>
	</tr>

	<tr>
		<td BGCOLOR="#CCCCCC"><a href="http://prdownloads.sourceforge.net/stella/Stella-4.0-win32.exe?download">Stella-4.0-win32.exe</a></td>
		<td BGCOLOR="#FFCC99">Binary installer (exe) for 32-bit Windows XP/Vista/7/8</td>
	</tr>

	<tr>
		<td BGCOLOR="#CCCCCC"><a href="http://prdownloads.sourceforge.net/stella/Stella-4.0-x64.exe?download">Stella-4.0-x64.exe</a></td>
		<td BGCOLOR="#FFCC99">Binary installer (exe) for 64-bit Windows XP/Vista/7/8</td>
	</tr>

	<tr>
		<td BGCOLOR="#CCCCCC"><a href="http://prdownloads.sourceforge.net/stella/Stella-4.0-windows.zip?download">Stella-4.0-windows.zip</a></td>
		<td BGCOLOR="#FFCC99">Binary ZIP (32-bit and 64-bit) for Windows XP/Vista/7/8</td>
	</tr>

	<tr>
		<td BGCOLOR="#CCCCCC"><a href="http://prdownloads.sourceforge.net/stella/Stella-4.0-macosx.dmg?download">Stella-4.0-macosx.dmg</a></td>
		<td BGCOLOR="#FFCC99">Binary DMG for MacOS X (32/64-bit, Intel CPU/10.5+ only)</td>
	</tr>

	<tr>
		<td BGCOLOR="#CCCCCC"><a href="http://prdownloads.sourceforge.net/stella/stella_4.0-1_i386.deb?download">stella_4.0-1_i386.deb</a></td>
		<td BGCOLOR="#FFCC99">Binary 32-bit DEB for Ubuntu 14.04 (Trusty Tahr)</td>
	</tr>

	<tr>
		<td BGCOLOR="#CCCCCC"><a href="http://prdownloads.sourceforge.net/stella/stella_4.0-1_amd64.deb?download">stella_4.0-1_amd64.deb</a></td>
		<td BGCOLOR="#FFCC99">Binary 64-bit DEB for Ubuntu 14.04 (Trusty Tahr)</td>
	</tr>

	<tr>
		<td BGCOLOR="#CCCCCC"><a href="http://prdownloads.sourceforge.net/stella/stella-4.0-2.i386.rpm?download">stella-4.0-2.i386.rpm</a></td>
		<td BGCOLOR="#FFCC99">Binary 32-bit RPM for Linux (generated by 'alien')</td>
	</tr>

	<tr>
		<td BGCOLOR="#CCCCCC"><a href="http://prdownloads.sourceforge.net/stella/stella-4.0-2.x86_64.rpm?download">stella-4.0-2.x86_64.rpm</a></td>
		<td BGCOLOR="#FFCC99">Binary 64-bit RPM for Linux (generated by 'alien')</td>
	</tr>

	<tr>
		<td BGCOLOR="#CCCCCC"><a href="http://prdownloads.sourceforge.net/stella/stella-4.0-src.tar.gz?download">stella-4.0-src.tar.gz</a></td>
		<td BGCOLOR="#FFCC99">Source code tarball for all systems</td>
	</tr>

	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>

	<tr>
		<td><b>Miscellaneous / Extras</b></td>
		<td>&nbsp;</td>
	</tr>

	<tr>
		<td BGCOLOR="#CCCCCC"><a href="http://prdownloads.sourceforge.net/stella/stella-snapshots-20130626.zip?download">stella-snapshots-20130626.zip</a></td>
		<td BGCOLOR="#FFCC99">Snapshot files for use in ROM launcher/ROM Info Viewer</td>
	</tr>

	<tr>
		<td BGCOLOR="#CCCCCC">
			<a href="http://sourceforge.net/project/showfiles.php?group_id=41847" target="_top">Sourceforge project page</a></td>
		<td BGCOLOR="#ddCC99">Older releases on the Sourceforge Stella project page</td>
	</tr>

	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>

</table>
<!---------------------------------------------------------------->

			</div>
			<div class="footer"><?php include("footer.php"); ?></div>
		</div>
		<div class="leftcolumn"><?php include("menu.html"); ?></div>
	</body>
</html>
